### ISSUE TITLE
Corrections sur la documentation

### ISSUE THREAD

**Issue by Zehir** [NeoFragCMS/neofrag-cms#13]
Bonjour,

Sur la documentation présente sur cette page;
https://neofr.ag/download.html

Concernant les extensions PHP, il faut aussi ceux la;
- mysql
- xml

A noter aussi que l'extension gd2 s’appelle en réalité gd.

Cordialement, Zehir

**Comment by michaelbilcot** [comment]
Salut,

D'accord on va faire les corrections
Merci

Par contre, pourquoi xml ?

**Comment by Zehir** [comment]
Salut,

Pour la fonction utf8_encode utilisée dans le fichier /var/www/config/password.php ligne 29.
D'après la doc il fait bien partie de l'extension xml;
http://php.net/manual/fr/function.utf8-encode.php

Et sans ce paquet j'ai bien l'erreur suivante dans le log apache

>  PHP Fatal error:  Uncaught Error: Call to undefined function utf8_encode() in /var/www/config/password.php:29
> Stack trace:
> #0 /var/www/neofrag/core/loader.php(166): include()
> #1 /var/www/neofrag/modules/user/controllers/index.php(367): Loader->library('password')
> #2 /var/www/neofrag/modules/user/controllers/index.php(27): m_user_c_index->login()
> #3 /var/www/neofrag/classes/controller.php(47): m_user_c_index->index()
> #4 /var/www/neofrag/core/router.php(169): Controller->method('index', Array)
> #5 /var/www/neofrag/core/router.php(65): Router->_load(Array)
> #6 /var/www/index.php(183): Router->exec()
> #7 {main}
> thrown in /var/www/config/password.php on line 29

**Comment by michaelbilcot** [comment]
Effectivement, je ne savais pas, merci
