### ISSUE TITLE
Security Issue : HTTPOnly cookies

### ISSUE THREAD

**Issue by ghost** [NeoFragCMS/neofrag-cms#19]
Session cookies MUST BE http only

**Comment by 0BuRner** [comment]
What are you talking about ? Can you give more information about what you said ?

**Comment by ghost** [comment]
![pict](https://cloud.githubusercontent.com/assets/19737074/20628688/c4360b78-b327-11e6-92f8-21c96f6af339.png)
Session & rights related cookies must be http only, so javascript can't steal your session using a xss vulnerability. 
If you're 'admin' right now, One could use the XSS to steal your session cookie and then get your permission level. I suggest you fix these as soon as possible since your customers arn't safe atm.
