### ISSUE TITLE
 Warning: Undefined property: User::$loader

### ISSUE THREAD

**Issue by jAKErCZ** [NeoFragCMS/neofrag-cms#25]
Hi, i update to website on version 1.6 and i found a bug.

```
Warning: Undefined property: User::$loader in /home2/jakerczs/public_html/inspire-gaming.cz/neofrag/classes/neofrag.php on line 113

Warning: Undefined property: Loader::$loader in /home2/jakerczs/public_html/inspire-gaming.cz/neofrag/classes/neofrag.php on line 113

Warning: Call to undefined method User::loader() in /home2/jakerczs/public_html/inspire-gaming.cz/neofrag/classes/neofrag.php on line 154
```

And not loaded 40% pages... and setting module,tamplates,witgets atd....

Please need fixed thx.

jAk3r

**Comment by BloberSh** [comment]
Did you removed all old widgets?
Widgets that were compatible with 0.1.5.3 are no longer available for 0.1.6. 
Except for a few exceptions that are already updated.

**Comment by jAKErCZ** [comment]
I installed 1 witgets and steam.... I disable steam witgets.... and no working...

**Comment by BloberSh** [comment]
That is strange. I am on your website and i don't see any error.

And please do not remove NeoFrag copyrights.

**Comment by jAKErCZ** [comment]
No... i never... i reinstall all system... and no work....

**Comment by BloberSh** [comment]
This method `::loader` is no more used in 0.1.6.

I assume you missed a file or something like that.

Send the file /neofrag/classes/neofrag.php from the clean 0.1.6 archive on your website using the ftp client.

**Comment by jAKErCZ** [comment]
No i download github version.... and edited config and look error....

**Comment by BloberSh** [comment]
Download it via the website : https://neofr.ag/download

**Comment by jAKErCZ** [comment]
I tested...

**Comment by BloberSh** [comment]
And by sending all files?

**Comment by jAKErCZ** [comment]
I installed new version and no funckion tampletes,modules,witgets.... i click to modules with admin Dashboard and 
will not appear....

**Comment by BloberSh** [comment]
I see your website right.

**Comment by jAKErCZ** [comment]
![image](https://cloud.githubusercontent.com/assets/7289889/24403176/fd948922-13bb-11e7-85b4-280548810c87.png)

but plays templates, modules, widgets, language

**Comment by BloberSh** [comment]
Is the database up to date?

**Comment by jAKErCZ** [comment]
So not read to me only when I use the https protocol, how to fix it?

**Comment by BloberSh** [comment]
Outdated. Old NF version.
