### ISSUE TITLE
Widget 'Navigation' not working with RocketLoader from Cloudflare

### ISSUE THREAD

**Issue by YetAnotherBinarySpace** [NeoFragCMS/neofrag-cms#34]
Hello.

With this option activated and set as 'automatic", you can't add any navigation widgets, add or remove links to navigation widgets in the live editor.

I figured out how to solve this issue, you need to edit the file ( Unfortunately, I don't know how to add a pull request on github )
/neofrag/widgets/navigation/views/admin.tpl.php and change <script type="text/javascript"> by <script data-cfasync="false" type="text/javascript"> at line 202.

**Source** : https://support.cloudflare.com/hc/en-us/articles/200169436-How-can-I-have-Rocket-Loader-ignore-my-script-s-in-Automatic-Mode-

Thanks for your attention

**Comment by BloberSh** [comment]
Out dated. Old NF version.
