### ISSUE TITLE
Faites-vous les push régulièrement ?

### ISSUE THREAD

**Issue by WebMatPro** [NeoFragCMS/neofrag-cms#35]
Bonjour à vous,

bravo pour votre énorme boulot.

J'aimerai vous aider et vous partager mon code via des pushs mais faites-les vous régulièrement ? pour éviter que je travaille sur un fichier non mis à jour.

Cordialement Mat.

**Comment by michaelbilcot** [comment]
Bonjour,

On push régulièrement, mais sur un dépôt privé, donc le GitHub est très en retard par rapport au dév en cours.
Le projet est encore en version Alpha, le code va énormément changé pour arrivé en version finale.
Merci de nous aider, mais je te conseillerais d'attendre la v1 ;)

FoxLey

**Comment by WebMatPro** [comment]
Merci pour ta réponse rapide.

Si je comprends bien, la beta est soon alors :) 

Avant 2018 ? histoire que je me prépare, j'ai un gros projets en fin d'année qui peut être, sera sur NeoFrag ;)

à bientôt

**Comment by michaelbilcot** [comment]
Soon je pense pas, avant 2018 ça me parait impossible.
On y travaille activement en tout cas ;)

**Comment by WebMatPro** [comment]
ok je note, je verrais alors avec la 1.7 qui incorporera le nouveau système de notification (si j'ai bien suivi), bon courage à vous.
