### ISSUE TITLE
Fatal error: Method View::__toString() in i18n/de and i18n/pt

### ISSUE THREAD

**Issue by renegade1337** [NeoFragCMS/neofrag-cms#36]
Fatal error: Method View::__toString() must not throw an exception, caught ParseError: syntax error, unexpected '(', expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in C:\xampp\htdocs\neofrag\neofrag\libraries\panels\widget.php on line 74

**Comment by michaelbilcot** [comment]
Hello,

Thanks for reporting the issue, i have fix and push (forced) the branches
