### ISSUE TITLE
[Admin] [Membres/Groupe] [Groupes]

### ISSUE THREAD

**Issue by PapyPoc** [NeoFragCMS/neofrag-cms#44]
Impossible de changer le groupe pour une personne
https://i.imgur.com/asupHhC.png

**Comment by SystemFailure38** [comment]
Même bug,
il faut modifier le fichier modules/user/controllers/admin.php
lignes 109 et 116 remplacer **user_id** par **id**
de mémoire il y a aussi un **nf_users** à remplacer par **nf_use**r (erreur dans le code sur la table qui n'existe pas)
