### ISSUE TITLE
[Admin] [Membres/Groupe] [Lien]

### ISSUE THREAD

**Issue by PapyPoc** [NeoFragCMS/neofrag-cms#45]
Lien incorrect pour l’édition d'un membre
Lien présent sur le site -> https://eagleone.ddns.net/fr/admin/edit/2/eresnova
Lien à modifié ->              https://eagleone.ddns.net/fr/admin/user/edit/2/eresnova

**Comment by SystemFailure38** [comment]
J'ai installé l'ALPHA 0.2.0.1 ca se corrige où dans le code sans attendre vos pushs sur github ?
