### ISSUE TITLE
Édition d'un profil - aucun changement

### ISSUE THREAD

**Issue by 0BuRner** [NeoFragCMS/neofrag-cms#46]
### Subject of the issue
Lorsque je modifie le profil, ça m'indique que le profil a bien été modifié mais dans la réalité il ne s'est rien passé.

### Your environment
* version of NeoFrag : 0.2.1
* version of PHP and list of activated extensions :
* version of your database (MySQL/MariaDB) :
* which browser and its version :

### Steps to reproduce
_Tell us how to reproduce this issue. 
Please provide a working demo as a base or a screenshot or video clip depending of your issue._

### Actual behaviour
Aucun changement dans le profil

### Expected behaviour
Le profil est modifié

**Comment by eResnova** [comment]
Remplacer dans le controleur index.php la ligne 164 :$profile->update();
Par : $profile->commit();

**Comment by VicVipers** [comment]
Merci bien!

**Comment by BloberSh** [comment]
Solved in DEV branch.
