### ISSUE TITLE
[Addon][Authenticator] connexion impossible

### ISSUE THREAD

**Issue by 0BuRner** [NeoFragCMS/neofrag-cms#51]
### Subject of the issue
Problème avec les Authentificateurs du moins ceux de steam et de google : les membres qui veulent se connecter avec ceci on ce message " Compte Steam inconnu".

### Your environment
* version of NeoFrag : 0.2.1

### Actual behaviour
![](https://cdn.discordapp.com/attachments/293324419512926208/518532834957197333/Capture_1.PNG)

### Expected behaviour
La connexion s'effectue correctement.

**Comment by sanishan** [comment]
Any Solution?
