### ISSUE TITLE
[Module][Admin] utilisateurs connectés

### ISSUE THREAD

**Issue by 0BuRner** [NeoFragCMS/neofrag-cms#52]
### Subject of the issue
Le nombre de personnes connectées indiqué dans la partie Administration semble incohérente avec la réalité.

### Your environment
* version of NeoFrag : 0.2.1
* version of PHP and list of activated extensions
* version of your database (MySQL/MariaDB)
* which browser and its version

### Actual behaviour
![](https://cdn.discordapp.com/attachments/293324419512926208/518533827975446538/Capture2.PNG)

**Comment by BloberSh** [comment]
Je n'ai pas ce soucis. Aurais-tu un screen des sessions actives?

**Comment by 0BuRner** [comment]
Ce n'est pas moi qui ai détecté le soucis mais 2 utilisateurs différents. Je n'ai fait que les retranscrire ;)
Faut regarder sur Discord qui a reporté le problème pour avoir plus d'infos.
