### ISSUE TITLE
[Module][Monitoring] conseil version PHP erroné

### ISSUE THREAD

**Issue by 0BuRner** [NeoFragCMS/neofrag-cms#53]
### Subject of the issue
Un conseil concernant la version de PHP est affiché : "Il est recommandé d'utiliser PHP 7" or la version de PHP utilisée est la 7.

### Your environment
* version of NeoFrag : 0.2.1 (Docker)

### Steps to reproduce
Tell us how to reproduce this issue. 
Please provide a working demo as a base or a screenshot or video clip depending of your issue.

### Actual behaviour
![image](https://user-images.githubusercontent.com/1845905/49339249-7add0100-f62f-11e8-9bfe-3b8567188f3d.png)

![image](https://user-images.githubusercontent.com/1845905/49339256-892b1d00-f62f-11e8-964e-c31aa2d474ec.png)

### Expected behaviour
Pas de conseil d'affiché

**Comment by BloberSh** [comment]
Soved by bb4998e
