### ISSUE TITLE
[Module][User][Admin] édition d'un membre - groupe décalage affichage

### ISSUE THREAD

**Issue by 0BuRner** [NeoFragCMS/neofrag-cms#54]
### Subject of the issue
Petit problème d'affichage de la liste des groupes lorsqu'on se trouve dans la page d'édition d'un membre.

### Your environment
* version of NeoFrag : 0.2.1 (Docker)
* which browser and its version : Chrome

### Steps to reproduce
Tell us how to reproduce this issue. 
Please provide a working demo as a base or a screenshot or video clip depending of your issue.

### Actual behaviour
![image](https://user-images.githubusercontent.com/1845905/49339317-1e2e1600-f630-11e8-8015-b44e34ec0808.png)

**Comment by eResnova** [comment]
Cas reproduit sur un affichage compact, petit écran ou smartphone.
