### ISSUE TITLE
[Module][Addons] Impossible d'ordonner les addons

### ISSUE THREAD

**Issue by eResnova** [NeoFragCMS/neofrag-cms#59]
### Subject of the issue
Lorsque l'on veut modifier l'ordre d'affichage des langues ou des authentificateurs, il est impossible de déplacer les items de la liste.

### Your environment
* Version of NeoFrag : 0.2.1

### Steps to reproduce
- Aller dans *Thèmes & Addons*
- Cliquer sur le bouton d'action d'une langue ou d'un authentificateur
- Cliquer sur l'action *Ordre*
- Essayer de déplacer un item de la liste

### Actual behaviour
Le sortable jQuery (jquery-ui) ne semble pas chargé et n'est donc pas actif sur les items.

### Expected behaviour
- Pouvoir réordonner les addons (langues et authentificateurs)

![sans titre-1](https://user-images.githubusercontent.com/7055737/49443720-72bac800-f7cd-11e8-9a55-9322b2d3c288.jpg)

**Comment by BloberSh** [comment]
Fixed with 0297879e4b6529bdad74d0b4e981aa2dadade22c
