### ISSUE TITLE
The requested URL /fr/index.php was not found on this server. 

### ISSUE THREAD

**Issue by luniun** [NeoFragCMS/neofrag-cms#65]
Bonjour,

Installation fraiche, Debian 9 , php7.3, mariadb.

Quand je vais sur http://monsite/index.php sa me retourne: 

> The requested URL /fr/index.php was not found on this server.

**Comment by 0BuRner** [comment]
Salut, chez quel hébergeur es-tu ? As-tu bien activé le module rewrite de Apache ?

**Comment by BloberSh** [comment]
Sans nouvelle de la part de @luniun je clos.
