### ISSUE TITLE
Drapeaux des pays ne s'affiche pas sur les événements

### ISSUE THREAD

**Issue by PapyPoc** [NeoFragCMS/neofrag-cms#67]
Sur tous ce qui est événement les drapeaux ne s'affiche pas.

**Comment by PapyPoc** [comment]
Dans modules/events/controllers/admin.php
Modifier la ligne 89 : 
<code>url('themes/default/images/flags/</code>
Par : 
<code>url('images/flags/</code>

Dans modules/events/views/event.tpl.php
Modifier la ligne 37 : 
<code>url('themes/default/images/flags/</code>
Par : 
<code>url('images/flags/</code>

Dans widgets/events/views/event.tpl.php
Modifier la ligne 15 : 
<code>url('themes/default/images/flags/</code>
Par : 
<code>url('images/flags/</code>

Dans widgets/events/views/matches.tpl.php
Modifier la ligne 22 : 
<code>url('themes/default/images/flags/</code>
Par : 
<code>url('images/flags/</code>

Dans widgets/events/views/upcoming.tpl.php
Modifier la ligne 19 : 
<code>url('themes/default/images/flags/</code>
Par : 
<code>url('images/flags/</code>

**Comment by BloberSh** [comment]
Merged in dev branch.
