### ISSUE TITLE
[Module][LiveEditor] Disposition commune sur zone "Contenu" ne change pas

### ISSUE THREAD

**Issue by BloberSh** [NeoFragCMS/neofrag-cms#72]
The slide to set "Disposition spécifique" in contenu area is not working. 

It still do it in the DB but is not updated directly in visual. 

We have to refresh the page to see the change.

**Comment by 0BuRner** [comment]
Quelle machine ce @eResnova ! En tout cas ça fait plaisir de voir que tout mon travail d'il y a plus d'1 an est enfin "utilisé" et n'a pas été inutile xD (les tickets créés).
Sinon, well done les gars, c'est cool de voir qu'il y a de la vie :)

**Comment by eResnova** [comment]
> Quelle machine ce @eResnova ! En tout cas ça fait plaisir de voir que tout mon travail d'il y a plus d'1 an est enfin "utilisé" et n'a pas été inutile xD (les tickets créés).
> Sinon, well done les gars, c'est cool de voir qu'il y a de la vie :)

Merci @0BuRner ! Ce n'est pas que le fruit de mon travail ! C'est l'équipe entière qui s'y remet ! :D

**Comment by 0BuRner** [comment]
Top les gars !
Et petite astuce, en mettant le numéro d'un ticket sous la forme #numero dans le commentaire d'un commit, il va faire le lien automatiquement et ça apparaîtra ici, plus simple pour voir les modifs liées à un ticket ;)
Genre le commentaire: "[Module][LiveEditor] Fix widget style default selection #72"
