### ISSUE TITLE
Problème module news Error 404

### ISSUE THREAD

**Issue by NuggaN85** [NeoFragCMS/neofrag-cms#82]
Bonjour a tous,

j'ai installer néofrag il y a 2 jours je mais des news tout marche bien mais une fois que les news passe a la page 2 3 etc il mais pas les news mais 404 error qui peux me dire d'ou viens le souci ?

merci d'avance.

https://gaming.infoforma.fr/

**Comment by michaelbilcot** [comment]
Salut,
merci pour ce signalement ;)
ce bug est résolu par ce commit https://github.com/NeoFrag/NeoFrag/commit/f9667e0a9d66f1bc98514e754e915a5505014e5c

**Comment by NuggaN85** [comment]
> Salut,
> merci pour ce signalement ;)
> ce bug est résolu par ce commit [f9667e0](https://github.com/NeoFrag/NeoFrag/commit/f9667e0a9d66f1bc98514e754e915a5505014e5c)

? pas trop compris résolu de quoi ? car vous me donner le lien mais pour forum pas pour les news

**Comment by michaelbilcot** [comment]
ce sont les modifications du fichier neofrag/libraries/pagination.php qui résolvent le bug ;)

**Comment by NuggaN85** [comment]
> ce sont les modifications du fichier neofrag/libraries/pagination.php qui résolvent le bug ;)

ah d'accord merci

**Comment by NuggaN85** [comment]
> ce sont les modifications du fichier neofrag/libraries/pagination.php qui résolvent le bug ;)

sa marche pas :/ tu aurais le fichier pour modules/forum/views/forum.tpl.php et neofrag/libraries/pagination.php ? car ca va pas chez moi sa reste sur le 404 error

**Comment by michaelbilcot** [comment]
Tu peux récupérer les fichiers complets depuis GitHub, c'est fait pour ;)
voilà les liens
https://raw.githubusercontent.com/NeoFrag/NeoFrag/f9667e0a9d66f1bc98514e754e915a5505014e5c/modules/forum/views/forum.tpl.php
https://raw.githubusercontent.com/NeoFrag/NeoFrag/f9667e0a9d66f1bc98514e754e915a5505014e5c/neofrag/libraries/pagination.php

**Comment by NuggaN85** [comment]
> Tu peux récupérer les fichiers complets depuis GitHub, c'est fait pour ;)
> voilà les liens
> https://raw.githubusercontent.com/NeoFrag/NeoFrag/f9667e0a9d66f1bc98514e754e915a5505014e5c/modules/forum/views/forum.tpl.php
> https://raw.githubusercontent.com/NeoFrag/NeoFrag/f9667e0a9d66f1bc98514e754e915a5505014e5c/neofrag/libraries/pagination.php

top merci :)

**Comment by NuggaN85** [comment]
part contre une fois changer sa mais une anomalie dans le monitor c'est un peux dommage a quand la prochaine mise a jours avec tout les bugs régler ?
