### ISSUE TITLE
[Module][Contact] JSON shown insteed of refresh

### ISSUE THREAD

**Issue by volkihars** [NeoFragCMS/neofrag-cms#83]
Bonsoir

[modules/contact]

Une fois qu'ont rempli les champs* on n'a une redirection sur cette page automatiquement. 

![Capture d’écran](https://user-images.githubusercontent.com/39424919/99136265-44ce9700-2624-11eb-9207-0e6649b3ee1f.png)

**Comment by BloberSh** [comment]
Lié au fait que sur le site officiel le formulaire est affiché sur un modal.
Correction partiel ici : https://github.com/BloberSh/NeoFrag/commit/c676e8273fd217b1fcc40eb7dc882a72e21d0624﻿

+ Autre problème lié => Anti flood KO (pas de refresh + affichage json au lieu de notif)
