### ISSUE TITLE
neofarg has a stored XSS vulnerability

### ISSUE THREAD

**Issue by g0h3aler** [NeoFragCMS/neofrag-cms#92]
It can be executed after writing the XSS Payload in the copyright setting in the background, and it is triggered when it is accessed in the foreground
![image](https://user-images.githubusercontent.com/38587657/114988967-87ddb080-9ec9-11eb-9a21-374c4a616841.png)
![image](https://user-images.githubusercontent.com/38587657/114988990-8f04be80-9ec9-11eb-8062-dcf76c2e0948.png)
![image](https://user-images.githubusercontent.com/38587657/114989040-9af08080-9ec9-11eb-8f83-1c6abe472b1b.png)

**Comment by 0BuRner** [comment]
Hello,

This security issue is of low level since you need to be admin in order to trigger that XSS, if I'm not mistaken.

Thanks for the report anyway.

**Comment by BloberSh** [comment]
Fixed in DEV bc4b1e292211444a3d4b1d86a65c4e169aea9955
